//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forge.RemoteDesktop.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forge.RemoteDesktop.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Title {
            get {
                return ResourceManager.GetString("Authentication_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string cbAuto {
            get {
                return ResourceManager.GetString("cbAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string cmDisconnect {
            get {
                return ResourceManager.GetString("cmDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        public static string cmFullScreen {
            get {
                return ResourceManager.GetString("cmFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit full screen.
        /// </summary>
        public static string cmFullScreenExit {
            get {
                return ResourceManager.GetString("cmFullScreenExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string cmPause {
            get {
                return ResourceManager.GetString("cmPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string cmReconnect {
            get {
                return ResourceManager.GetString("cmReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh screen.
        /// </summary>
        public static string cmRefreshScreen {
            get {
                return ResourceManager.GetString("cmRefreshScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string cmResume {
            get {
                return ResourceManager.GetString("cmResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a file.
        /// </summary>
        public static string cmSendFile {
            get {
                return ResourceManager.GetString("cmSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set quality.
        /// </summary>
        public static string cmSetQuality {
            get {
                return ResourceManager.GetString("cmSetQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this menu.
        /// </summary>
        public static string cmShowMenu {
            get {
                return ResourceManager.GetString("cmShowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to cancel file sending? This will end your remote session too..
        /// </summary>
        public static string Dialog_AbortFileSend {
            get {
                return ResourceManager.GetString("Dialog_AbortFileSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string Dialog_AllFiles {
            get {
                return ResourceManager.GetString("Dialog_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        public static string Error_AuthFailed {
            get {
                return ResourceManager.GetString("Error_AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file. Reason:.
        /// </summary>
        public static string Error_CannotOpenFile {
            get {
                return ResourceManager.GetString("Error_CannotOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to login. Reason: {0}.
        /// </summary>
        public static string Error_FailedToLogin {
            get {
                return ResourceManager.GetString("Error_FailedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send file. Reason: {0}.
        /// </summary>
        public static string Error_FailedToSendFile {
            get {
                return ResourceManager.GetString("Error_FailedToSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start network. Reason: {0}.
        /// </summary>
        public static string Error_FailedToStartNetwork {
            get {
                return ResourceManager.GetString("Error_FailedToStartNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Desktop Client.
        /// </summary>
        public static string FormTitle {
            get {
                return ResourceManager.GetString("FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the desktop quality:.
        /// </summary>
        public static string lDesktopQuality {
            get {
                return ResourceManager.GetString("lDesktopQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string lPassword {
            get {
                return ResourceManager.GetString("lPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string lUserName {
            get {
                return ResourceManager.GetString("lUserName", resourceCulture);
            }
        }
    }
}
