//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forge.DatabaseManagement.SqlServer2008.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Forge.DatabaseManagement.SqlServer2008.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER DATABASE [{0}] COLLATE {1}.
        /// </summary>
        internal static string AlterDatabaseCollation {
            get {
                return ResourceManager.GetString("AlterDatabaseCollation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM master.dbo.syslogins db WHERE db.loginname = @P0.
        /// </summary>
        internal static string CheckLogin {
            get {
                return ResourceManager.GetString("CheckLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE DATABASE [{0}].
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE LOGIN {0} WITH PASSWORD = &apos;{1}&apos;, CHECK_EXPIRATION = OFF, CHECK_POLICY = OFF.
        /// </summary>
        internal static string CreateLogin {
            get {
                return ResourceManager.GetString("CreateLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM master.dbo.sysdatabases db WHERE db.name = @P0.
        /// </summary>
        internal static string DatabaseCheck {
            get {
                return ResourceManager.GetString("DatabaseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DATABASEPROPERTYEX(&apos;{0}&apos;, &apos;Collation&apos;) SQLCollation.
        /// </summary>
        internal static string GetDatabaseCollation {
            get {
                return ResourceManager.GetString("GetDatabaseCollation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER AUTHORIZATION ON DATABASE::{0} TO [{1}].
        /// </summary>
        internal static string SetDatabaseOwner {
            get {
                return ResourceManager.GetString("SetDatabaseOwner", resourceCulture);
            }
        }
    }
}
