/* *********************************************************************
 * Date: 29 Jul 2013
 * Created by: Zoltan Juhasz
 * E-Mail: forge@jzo.hu
***********************************************************************/

using System;
using System.Runtime.InteropServices;

namespace Forge.Native.Structures
{

    /// <summary>
    /// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
    /// http://msdn.microsoft.com/en-us/library/windows/desktop/ms646269(v=vs.85).aspx
    /// </summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public struct HardwareInput
    {

        /// <summary>
        /// The message generated by the input hardware.
        /// </summary>
        public uint UMsg;

        /// <summary>
        /// The low-order word of the lParam  parameter for UMsg.
        /// </summary>
        public ushort WParamL;

        /// <summary>
        /// The high-order word of the lParam  parameter for UMsg.
        /// </summary>
        public ushort WParamH;

    }

}
